# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nibscbioinformatics-humgen-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=2.7.15
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.7
  - bioconda::humann2=2.8.1
  - anaconda::wget= 1.20.1
  - bwa=0.7.17
  - samtools=1.9
  - gatk4=4.1.5.0
  - snpeff=4.3.1t
  - cutadapt=2.3
